### ISSUE TITLE
Panel data appears to have a problem

### ISSUE THREAD

**Issue by CGTZA2** [kjhealy/gssr#1]
Very useful package!  Thanks
However, when loading the panel data set, there seems to be a snag.  
The id and wave combinations make sense for waves 2 and 3, but wave 1 seems disconnected.
Thus, if we check the unique id codes for the waves, 

gss_panel_long %>% 
    filter(wave > 1) %>% 
    distinct(id) %>% 
    nrow()

gss_panel_long %>% 
  filter(wave == 1) %>% 
  distinct(id) %>% 
  nrow()
  
we get 1552 and 2044, respectively.

Or consider if we look only at id == 10750

gss_panel_long %>% 
  select(wave, id) %>% 
  filter(id == 10750) 

we get 

# Panel data:    2 x 2
# entities:      id [1]
# wave variable: wave [1, 2, 3 (3 waves)]
  id     wave
  <fct> <dbl>
1 10750     2
2 10750     3
>

**Comment by kjhealy** [comment]
Thanks; I should be able to take a look at this later this week.

**Comment by kjhealy** [comment]
Got to this sooner than expected. Think I've sorted out the problem you identified (and also simplified the panel data—they are just tibbles now). I also added all three of the 3-wave panels, so there's no longer a data object `gss_panel_long`, but rather `gss_panel06_long`, `gss_panel08_long`, and `gss_panel10_long`. Rows are uniquely identified by `firstid`, the `id` variable is the GSS's per-wave `id_1`, `id_2`, and `id_3` variables. You can look at the attrition over time by e.g. 

`
gss_panel06_long %>% 
  select(wave, id) %>%
  group_by(wave) %>%
  summarize(observed = n_distinct(id),
            missing = sum(is.na(id)))
`

**Comment by CGTZA2** [comment]
Thanks, that's great.  I have taken a look at the 06 tibble, and it works well.  Data very useful indeed; a great initiative. Would be nice to get some of the other big longitudinal surveys into R packages, but ESS, UKDATA would need some persuading...
