### ISSUE TITLE
Update with 2022 data

### ISSUE THREAD

**Issue by jrpepin** [kjhealy/gssr#10]
More a request than an issue -- Will you be updating the GSS cumulative data file download to point to the 2022 data release (please!)? And, if I'm greedy (I am), the gss_get_yr() to fetch 2021 and 2022?

**Comment by hardin47** [comment]
Is there a way to get the 2021 data?  `gss_get_yr(2021)` produces the following errors:

Fetching: https://gss.norc.org/documents/stata/2021_stata.zip
! Multiple files in zip: reading ''2021 XSEC Methodological Primer.pdf''
Error: Failed to parse /private/var/folders/n8/4xxznh1x29q4sg4cf_hcqqv40000gp/T/RtmpZISYN1/file8b03753840df: This version of the file format is not supported.

Thanks!

**Comment by kjhealy** [comment]
Belatedly, @hardin47 and @jrpepin, `gssr` has been updated to include the 1972-2022 cumulative file, the 2022 panel data release, and `gss_get_yr()` can correctly grab all the years from 1972 to 2022 individually. More details about these changes are in the Readme and the package website
