### ISSUE TITLE
SSL: no alternative certificate subject name matches target host name 

### ISSUE THREAD

**Issue by lindsaypoirier** [kjhealy/gssr#6]
Thanks for this great package! I'm having an issue with getting single year data: 

``` r
library(gssr)
#> Package loaded. To attach the GSS data, type data(gss_all) at the console.
#> For the codebook, type data(gss_doc).
#> For the panel data and documentation, type e.g. data(gss_panel08_long) and data(gss_panel_doc).
gss21 <- gss_get_yr(2021)
#> Fetching: http://www.gss.norc.org/documents/stata/2021_stata.zip
#> Error in curl_download(target, tf): SSL: no alternative certificate subject name matches target host name 'www.gss.norc.org'
```
Any recommendations?

**Comment by kjhealy** [comment]
Hmm they may have done away with `www.gssr.norc.org` and are just using `gssr.norc.org`. I'll take a look to see if that's what's actually happening.

**Comment by kjhealy** [comment]
@lindsaypoirier Yes, that's what was happening. I've updated the package to fix this. If you reinstall `gssr` it should work as expected now.

**Comment by lindsaypoirier** [comment]
Fantastic! Working now. Thanks for your swift help on this!
